// Hardcoded pool of starter questions for a fresh / empty chat.
// Shown 3-at-a-time (random) in the middle of the screen; tapping one sends
// it straight to the AI. No network request needed.

export const SUGGESTION_POOL: string[] = [
  "Explain quantum computing in simple terms",
  "Write a haiku about the ocean",
  "What are 5 healthy breakfast ideas?",
  "Explain black holes like I'm 10 years old",
  "Write a short motivational speech",
  "How do I start learning Python?",
  "What is the difference between AI and ML?",
  "Give me 3 creative birthday gift ideas",
  "Explain photosynthesis step by step",
  "Write a funny short story about a robot",
  "What are the best time management tips?",
  "How does the stock market work?",
  "Explain gravity in one paragraph",
  "Write a professional resignation email",
  "What are 5 ways to reduce stress?",
  "How do airplanes fly?",
  "Tell me a mind-blowing space fact",
  "Write a poem about rainy days",
  "What is blockchain in simple words?",
  "Give me a 7-day workout plan for beginners",
  "Explain the theory of relativity briefly",
  "How can I improve my English vocabulary?",
  "Write a catchy tagline for a coffee shop",
  "What causes dreams when we sleep?",
  "List 10 fun facts about cats",
  "How do I cook perfect pasta?",
  "Explain DNA like I'm a beginner",
  "Write a bedtime story for a 5-year-old",
  "What are the benefits of meditation?",
  "How does GPS know my location?",
  "Give me ideas for a weekend trip on a budget",
  "What is the Pythagorean theorem used for?",
  "Write a LinkedIn post about teamwork",
  "Explain climate change in simple terms",
  "How can I save money every month?",
  "What is the fastest animal on Earth?",
  "Teach me a quick mental math trick",
  "Write a dialogue between two astronauts",
  "What are good habits for better sleep?",
  "How do vaccines work?",
  "Give me 5 startup ideas using AI",
  "Explain the water cycle with an example",
  "Write a birthday wish for my best friend",
  "What is the capital of Australia?",
  "How can I be more productive working from home?",
  "Tell me the history of the internet briefly",
  "Write a product description for sneakers",
  "What are examples of renewable energy?",
  "Explain how rainbows form",
  "Give me tips for public speaking",
  "How do I write a good resume?",
  "What is machine learning with an example?",
  "Write a limerick about a programmer",
  "How can I learn a new language fast?",
  "What is the deepest part of the ocean?",
  "Explain how email actually works",
  "Give me 5 journaling prompts",
  "What foods boost brain power?",
  "How did the pyramids get built?",
  "Write an Instagram caption for a sunset photo",
  "What is the difference between weather and climate?",
  "How can I overcome procrastination?",
  "Explain electric cars vs petrol cars",
  "Tell me a riddle that's hard to solve",
  "What are the 7 wonders of the world?",
  "How do I meditate for the first time?",
  "Write a thank-you note for an interview",
  "What is the speed of light?",
  "Give me 3 easy vegetarian dinner recipes",
  "Explain evolution in simple words",
  "How can I improve my memory?",
  "Write a horror story in 3 sentences",
  "What is 5G and why does it matter?",
  "How do I plan a daily routine?",
  "Tell me about the Mars rover missions",
  "Write a slogan for an eco-friendly brand",
  "What is emotional intelligence?",
  "How does Wi-Fi work?",
  "Give me ideas for a YouTube channel",
  "Explain fractions with a pizza example",
  "What are the signs of dehydration?",
  "How can I stay motivated to exercise?",
  "Write a welcome speech for a school event",
  "What is the largest planet in our solar system?",
  "How do I bake chocolate chip cookies?",
  "Explain what a neural network does",
  "Give me 5 ways to be kinder every day",
  "What is the meaning of mindfulness?",
  "How do submarines go underwater?",
  "Write a short mystery story opening",
  "What are the best books for beginners in psychology?",
  "How can I grow plants indoors?",
  "Explain time zones with an example",
  "What is the tallest mountain in the world?",
  "Give me a packing checklist for travel",
  "How do I stay focused while studying?",
  "Write a funny tweet about Mondays",
  "What is the human genome project?",
  "How can I make my mornings better?",
  "Explain supply and demand simply",
];

/** Return `count` random unique questions from the pool (Fisher–Yates). */
export function pickRandomSuggestions(count = 3): string[] {
  const copy = [...SUGGESTION_POOL];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy.slice(0, Math.max(0, Math.min(count, copy.length)));
}
